# Generated by Django 3.0.10 on 2020-09-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meallist', '0002_auto_20200921_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='meals',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
