# Generated by Django 3.0.10 on 2020-09-22 08:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('meallist', '0004_auto_20200921_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meals',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 9, 22, 8, 36, 46, 496976, tzinfo=utc)),
        ),
    ]
