# Generated by Django 3.0.10 on 2020-09-22 08:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('meallist', '0005_auto_20200922_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='meals',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 22, 8, 40, 41, 710318, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='meals',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 22, 8, 40, 41, 710398, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='meals',
            name='date',
            field=models.DateField(),
        ),
    ]
