# Generated by Django 3.0.10 on 2020-09-23 09:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('meallist', '0006_auto_20200922_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meals',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 23, 9, 16, 37, 512104, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='meals',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 23, 9, 16, 37, 512133, tzinfo=utc)),
        ),
    ]
